### ISSUE TITLE
[case-insensitive] sx9dev

### ISSUE THREAD

**Issue by SX-9** [Global-Chat-Bot/easter-eggs#7]
## Request Information
**User**: sx9dev (882595027132493864)
**Guild**: Global Chat Support (1067023529226293248)

## Prompt
```
sx9dev
```

## Output
```
sx9dev is the best dev to exists!
```

**Comment by WilliamDavidHarrison** [comment]
Added in https://github.com/Global-Chat-Bot/easter-eggs/commit/2834d41f9942195d82f1b168d2e9875c743e928e
